using UnityEngine;
using UnityEngine.TextCore.Text;

namespace SpawnRowDuel.View.Cards
{
    public enum UiFont { DisplayRegular, DisplayBold, DisplayBlack, BodyRegular, BodyBold, BodyItalic }

    /// <summary>
    /// The view's asset handles, in one Resources-loaded object.
    ///
    /// Runtime code cannot reach AssetDatabase, and threading six font references through every
    /// constructor from the scene root down to a card's ability line is the kind of plumbing that
    /// quietly stops being maintained. One asset, generated by the font pipeline, loaded once.
    ///
    /// A null font is survivable on purpose: the frame falls back to the engine default rather than
    /// throwing, so a project that has not run tools/regen-fonts.sh yet still boots - it just looks
    /// wrong, which the coverage test says out loud.
    /// </summary>
    public sealed class ViewAssets : ScriptableObject
    {
        public const string ResourcePath = "ViewAssets";

        [SerializeField] internal FontAsset displayRegular;
        [SerializeField] internal FontAsset displayBold;
        [SerializeField] internal FontAsset displayBlack;
        [SerializeField] internal FontAsset bodyRegular;
        [SerializeField] internal FontAsset bodyBold;
        [SerializeField] internal FontAsset bodyItalic;

        static ViewAssets _instance;
        static bool _looked;

        public static ViewAssets Instance
        {
            get
            {
                if (_instance == null && !_looked)
                {
                    _looked = true;
                    _instance = Resources.Load<ViewAssets>(ResourcePath);
                    if (_instance == null)
                        Debug.LogWarning("ViewAssets is missing - run tools/regen-fonts.sh");
                }
                return _instance;
            }
        }

        public static FontAsset Font(UiFont which)
        {
            var a = Instance;
            if (a == null) return null;
            switch (which)
            {
                case UiFont.DisplayRegular: return a.displayRegular;
                case UiFont.DisplayBold: return a.displayBold;
                case UiFont.DisplayBlack: return a.displayBlack;
                case UiFont.BodyBold: return a.bodyBold;
                case UiFont.BodyItalic: return a.bodyItalic;
                default: return a.bodyRegular;
            }
        }
    }
}
