using System;
using UnityEngine;
using SpawnRowDuel.Rules;

namespace SpawnRowDuel.Data
{
    public enum CardKind : byte
    {
        Creature = 0, Spell = 1, Structure = 2, Commander = 3, Element = 4, Token = 5,
    }

    /// <summary>
    /// One card row from cards.json as a committed, diffable asset. GENERATED by the importer -
    /// never hand-edited; to change a card you edit the JS registry, re-export, re-import
    /// (design 03 s5.1, one-way flow).
    ///
    /// One SO type with a kind discriminator rather than four sibling types, because the deck
    /// builder, hand, graveyard and snapshots all hold heterogeneous card lists. Fields not
    /// relevant to a kind stay at their defaults.
    ///
    /// Unity cannot serialize Nullable, so the registry's load-bearing null-vs-0 distinction
    /// (det/reap/wardhp/grow/hatch, spell val) is carried as -1 == "the JS null". The projection
    /// methods convert back before anything reaches the rules core.
    /// </summary>
    [CreateAssetMenu(menuName = "Spawn Row Duel/Card Definition", fileName = "card")]
    public sealed class CardDefinition : ScriptableObject
    {
        // ── identity ─────────────────────────────────────────────────────────
        [SerializeField] internal string exportKey;      // "fire|Magmaw", "forge:fire", "light_dark"
        [SerializeField] internal CardKind kind;
        [SerializeField] internal string displayName;    // == nm, identity in the JS - keep exact
        [SerializeField] internal string slug;           // art lookup key
        [SerializeField] internal Element element;       // None for neutral spells/traps
        [SerializeField] internal bool isNeutral;        // the JS color was null
        [SerializeField] internal bool isPlayable = true; // false for divine; == deckable for elements

        /// <summary>Position within this kind's registry section. ORDER IS LOAD-BEARING: pool
        /// order feeds deckOf, commander order feeds the random pick, build-list and spell order
        /// feed the AI and the deck factory. The database index array is sorted by exportKey for
        /// stable diffs, so this is how registry order is reconstructed.</summary>
        [SerializeField] internal int registryIndex = -1;

        // ── shared ───────────────────────────────────────────────────────────
        [SerializeField] internal int cost;              // c

        // ── creature ─────────────────────────────────────────────────────────
        [SerializeField] internal int poolIndex = -1;
        [SerializeField] internal int attack;            // a
        [SerializeField] internal int health;            // h (also structure hp, commander unused)
        [SerializeField] internal int upkeep;            // up
        [SerializeField] internal bool firstStrike;      // fs - a FLAG, not a keyword
        [SerializeField] internal Keyword keyword;
        [SerializeField] internal int detonate = -1;     // -1 == null
        [SerializeField] internal int reap = -1;
        [SerializeField] internal int wardHp = -1;
        [SerializeField] internal int grow = -1;
        [SerializeField] internal int hatch = -1;
        [SerializeField] internal bool entrench;
        [SerializeField] internal Tribe tribe;
        [SerializeField] internal Subtype subtype;
        [SerializeField] internal string intoName = ""; // Chrysalis hatch form; "" == none
        [SerializeField] internal int intoAttack;
        [SerializeField] internal int intoHealth;

        // ── spell / trap ─────────────────────────────────────────────────────
        [SerializeField] internal bool isTrap;
        [SerializeField] internal SpellEffect spellEffect;
        [SerializeField] internal int spellValue = -1;   // -1 == null
        [SerializeField] internal SpellTarget spellTarget;
        [SerializeField] internal TrapTrigger trapTrigger;
        [SerializeField] internal string glyph = "";     // ic - presentation

        // ── structure ────────────────────────────────────────────────────────
        [SerializeField] internal string buildId = "";   // bid - the FAMILY id
        [SerializeField] internal StructEffect structEffect;
        [SerializeField] internal int structValue;       // val
        [SerializeField] internal int support;           // sup - MAY BE NEGATIVE (tower -2)
        [SerializeField] internal string[] prereq = new string[0];
        [SerializeField] internal string upgradedFrom = "";  // from; "" == menu-buildable root
        [SerializeField] internal string[] upgradesTo = new string[0];  // up2
        [SerializeField] internal RowGate rowGate;
        [SerializeField] internal bool buildable;

        // ── commander (life/baseWorkers double as element hp/wk) ─────────────
        [SerializeField] internal int life;              // hp
        [SerializeField] internal int baseWorkers;       // wk
        [SerializeField] internal Element[] colors = new Element[0];
        [SerializeField] internal string[] buildList = new string[0];
        [SerializeField] internal bool dual;

        // ── element display identity (kind == Element only) ──────────────────
        [SerializeField] internal string glyphKanji = "";
        [SerializeField] internal string colorHex = "";
        [SerializeField] internal string accentHex = "";
        [SerializeField] internal string deepHex = "";
        [SerializeField] internal string[] bgStops = new string[0];

        // ── flavour + art ────────────────────────────────────────────────────
        [TextArea(2, 5)]
        [SerializeField] internal string description = "";
        [SerializeField] internal Sprite cardArt;        // null is EXPECTED - placeholders ship (G1)
        [SerializeField] internal Sprite fieldArt;       // standee cut-out; null borrows cardArt

        // ── read-only surface ────────────────────────────────────────────────
        public string ExportKey { get { return exportKey; } }
        public CardKind Kind { get { return kind; } }
        public string DisplayName { get { return displayName; } }
        public string Slug { get { return slug; } }
        public Element Element { get { return element; } }
        public int Cost { get { return cost; } }
        public int RegistryIndex { get { return registryIndex; } }
        public Sprite CardArt { get { return cardArt; } }
        public Sprite FieldArt { get { return fieldArt; } }
        public bool HasFieldArt { get { return fieldArt != null; } }
        public string Description { get { return description; } }
        public string Glyph { get { return glyph; } }

        /// <summary>"&lt;color|neutral&gt;|&lt;nm&gt;" - the save/deck compatibility surface.</summary>
        public string DeckKeyString
        {
            get { return (isNeutral ? "neutral" : ElementNames.ToKey(element)) + "|" + displayName; }
        }

        private static int? FromSentinel(int v) { return v < 0 ? (int?)null : v; }

        // ── projections into the PURE rules records ──────────────────────────
        // The rules core never sees this ScriptableObject type.

        public CreatureCard ToCreatureCard()
        {
            HatchForm into = string.IsNullOrEmpty(intoName)
                ? null : new HatchForm(intoName, intoAttack, intoHealth);
            return new CreatureCard(new CardId(displayName), displayName, element, poolIndex,
                cost, attack, health, upkeep, firstStrike, entrench, keyword,
                FromSentinel(detonate), FromSentinel(reap), FromSentinel(wardHp),
                FromSentinel(grow), FromSentinel(hatch),
                into, tribe, subtype, isPlayable, slug);
        }

        public SpellCard ToSpellCard()
        {
            return new SpellCard(new CardId(displayName), displayName, cost, isTrap,
                spellEffect, FromSentinel(spellValue), spellTarget, trapTrigger, glyph, slug);
        }

        public StructureDef ToStructureDef()
        {
            return new StructureDef(exportKey, new StructId(buildId), displayName, cost, health,
                structEffect, structValue, support,
                isNeutral ? Element.None : element,
                prereq,
                string.IsNullOrEmpty(upgradedFrom) ? StructId.None : new StructId(upgradedFrom),
                upgradesTo, rowGate, buildable, glyph, slug, description);
        }

        public CommanderDef ToCommanderDef()
        {
            return new CommanderDef(new CommanderId(exportKey), displayName, life, baseWorkers,
                colors, dual, buildList, description);
        }

        public ElementDef ToElementDef()
        {
            return new ElementDef(element, ElementNames.ToKey(element), displayName, glyphKanji,
                life, baseWorkers, isPlayable, colorHex, accentHex, deepHex, bgStops, description);
        }

#if UNITY_EDITOR
        /// <summary>Importer-only mutation surface: runtime code cannot write card data.</summary>
        public void __EditorApply(Action<CardDefinition> mutate)
        {
            mutate(this);
        }
#endif
    }
}
