#!/usr/bin/env node
// Every non-ASCII character the game puts on screen, collected from the reference build's source
// and its card data, written to docs/unity/spec/glyphs.txt.
//
// This exists because "tofu risk" was an open P0 and a hope is not a plan: the Unity font pipeline
// builds its fallback chain from this list, and a coverage test fails the build if any character
// in it has no glyph in any font of the chain. A missing glyph then costs a red test instead of a
// row of empty boxes discovered in a screenshot.
//
// The JS is the vocabulary source while it is still the reference build (PORT_PLAN §4). New UI
// text authored in C# adds to the list by hand - the file is committed, not generated at build.
//
// Usage: node tools/export_glyphs.mjs [--check]

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'docs/unity/spec/glyphs.txt');

const sources = [
  ...readdirSync(join(ROOT, 'src/js')).filter((f) => f.endsWith('.js')).map((f) => join(ROOT, 'src/js', f)),
  join(ROOT, 'docs/unity/spec/cards.json'),
  join(ROOT, 'index.html'),
];

const counts = new Map();
for (const file of sources) {
  if (!existsSync(file)) continue;
  for (const ch of readFileSync(file, 'utf8')) {
    const code = ch.codePointAt(0);
    if (code > 127) counts.set(ch, (counts.get(ch) || 0) + 1);
  }
}

// Sorted by codepoint so the file diffs meaningfully rather than by whatever happened to be scanned
const chars = [...counts.keys()].sort((a, b) => a.codePointAt(0) - b.codePointAt(0));

const body = chars.join('') + '\n';
const header = `# ${chars.length} non-ASCII glyphs the game renders. Generated by tools/export_glyphs.mjs.\n`
  + '# One line of characters below; lines starting with # are comments.\n';
const text = header + body;

if (process.argv.includes('--check')) {
  const current = existsSync(OUT) ? readFileSync(OUT, 'utf8') : '';
  if (current !== text) {
    console.error('glyphs.txt is stale — run: node tools/export_glyphs.mjs');
    process.exit(1);
  }
  console.log(`glyphs.txt is current (${chars.length} glyphs)`);
} else {
  writeFileSync(OUT, text, 'utf8');
  console.log(`wrote ${chars.length} glyphs to docs/unity/spec/glyphs.txt`);
  console.log(chars.join(' '));
}
